### ISSUE TITLE
In-Home-Switching Not Appear

### ISSUE THREAD

**Issue by myfire888** [jakibaki/In-Home-Switching#10]
on my pc, inhomeswitching working right
on my tablet microsoft surface pro 2017, when I tried to run the program, nothing happened
have tried run as admin, still nothing happened
surface pro 2017 with windows 10 pro, net framework 3.5 and 4.7 installed
can u pls help? thx

**Comment by xboxexpert** [comment]
Scp drivers installed?

**Comment by myfire888** [comment]
Omg u're right. I skip that step automatically cause in my mind i remembered to only download the inhomeswitching.exe.
It should be that, but i'm outside atm. Will try it later when i'm home.thx very much

**Comment by D-VAmpire** [comment]
Have you tried yet? 
If yes (and the drivers were in fact the problem) I would like to close this issue.
