### ISSUE TITLE
(this is a request not a problem) 

### ISSUE THREAD

**Issue by SplatHaxUser3** [jakibaki/In-Home-Switching#40]
So I love your client and I already tried it (the idea with the Overclocking is great Btw) but I really would want to see a android client! Before you sys it's not possible, it probably is with root
Maybe you could do it someday or whenever you want to do it! (would be interesting to play phone games without having a loud pc in front of you)

**Comment by giorgioshine** [comment]
What's the point of creating an another Android app for game streaming when there are already a lot of good apps that do that.

**Comment by jakibaki** [comment]
This is out of scope for this project, sorry.
