### ISSUE TITLE
doesn't work on windows 10

### ISSUE THREAD

**Issue by twinec** [jakibaki/In-Home-Switching#50]
On my computer, when I open the app, nothing happens. It loads for a bit and nothing comes up, not even in task manager as a background process.

**Comment by daw2-cognom19** [comment]
I dont know how to do this... Do you solved?

**Comment by twinec** [comment]
> I dont know how to do this... Do you solved?

I don't know what you are saying

**Comment by ajc11196** [comment]
If you install the spc drivers it will work! was doing this for me until I installed them...

**Comment by twinec** [comment]
thank you so much! That worked!
